src/conf/urls.py
from django.shortcuts import HttpResponseRedirect
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('movies/', include('movies.urls')),
]

if settings.DEBUG:
	urlpatterns	+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/movies/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
	
	# urls relating to user login and registration
	path('', views.MovieList.as_view(template_name="movies/list.html"), name="list"),
	path('movie/<int:pk>', views.MovieDetail.as_view(template_name="movies/detail.html"), name="detail"),
	path('movie/<int:movie_id>/vote', views.CreateVote.as_view(), name="CreateVote"),
	path('movie/<int:movie_id>/vote/<int:pk>', views.UpdateVote.as_view(), name="UpdateVote"),
	path('movie/<int:movie_id>/image/upload', views.MovieImageUpload.as_view(), name="MovieImageUpload"),
	path('movie/<int:movie_id>/comment', views.AddComment.as_view(), name="AddComment"),
	path('q/search', views.SearchView.as_view(), name="question_search"),
]

src/movies/models.py
from django.db import models
from django.db.models.aggregates import Sum
from django.conf import settings
from uuid import uuid4
from taggit.managers import TaggableManager

# Create your models here.
'''
class PersonManager(models.Manager):
	def all_with_prefetched_movies(self):
		qs = self.get_queryset()
		qs = qs.prefetch_related('directed', 'writing_credits', 'roles')
		return qs
'''
class Person(models.Model):
	first_name = models.CharField(max_length = 140)
	last_name = models.CharField(max_length = 140)
	born = models.DateField()
	died = models.DateField(blank=True, null=True)
	#defining the custom made manager
	#objects = PersonManager()

	class Meta:
		ordering = ('last_name', 'first_name')

		def __str__(self):
			if self.died:
				return '{}, {} ({}-{})'.format(self.last_name, self.first_name, self.born, self.died)
			return '{}, {} ({})'.format(self.last_name, self.first_name, self.born)


'''
class MovieManager(models.Manager):

	def all_with_related_persons(self):
		qs = self.get_queryset()
		qs = qs.select_related('director')
		qs = qs.prefetch_related('writers', 'actors')
		return qs

	def all_with_related_persons_and_score(self):
		qs = self.all_with_related_persons()
		qs = self.prefetch_related('votes')
		return qs

	def top_movies(self, limit):
		qs = self.get_queryset()
		qs = qs.exclude(score=0)
		qs = qs.order_by('-score')
		qs = qs[:limit]
		return qs
'''

class Movie(models.Model):
	NOT_RATED = 0
	RATED_G = 1
	RATED_PG = 2
	RATED_R = 3
	RATINGS = ((NOT_RATED,'NR - NOT RATED'),(RATED_G, 'G - General Audiences'), (RATED_PG, 'PG - Parental Guidance'), (RATED_R, 'R - Restricted'))

	score = models.IntegerField(default=0, blank=True, null=True)
	visits = models.IntegerField(default=0, blank=True, null=True)
	title = models.CharField(max_length = 140)
	plot = models.TextField()
	year = models.PositiveIntegerField()
	rating = models.IntegerField(choices = RATINGS,default = NOT_RATED)
	runtime = models.PositiveIntegerField()
	website = models.URLField(blank= True)

	#relationships
	director = models.ForeignKey(to='Person', on_delete=models.SET_NULL, related_name='directed', null=True, blank=True)
	writers = models.ManyToManyField(to='Person', related_name='writing_credits', blank=True)
	actors = models.ManyToManyField(to='Person', through='Role',related_name='acting_credits', blank=True)
	

	tags = TaggableManager()
	#defining the custom made manager
	#objects = MovieManager()
	def as_elasticsearch_dict(self):
		return {
			'_id':self.id,
			'_type':'doc',
			'text':'{}\n{}'.format(self.title, self.plot),
			'title':self.title,
			'id':self.id,
			'year':self.year,
			'runtime':self.runtime,
		}

	class Meta:
		ordering = ('-year', 'title')

	def __str__(self):
		return '{} ({})'.format(self.title, self.year)



class Role(models.Model):
	movie = models.ForeignKey(to='Movie', related_name='roles', on_delete=models.DO_NOTHING)
	person = models.ForeignKey(to='Person',related_name='roles', on_delete=models.DO_NOTHING)
	name = models.CharField(max_length=140)

	def __str__(self):
		return "{} {} {} ".format(self.movie__id, self.person__id, self.name)

	class Meta:
		unique_together = ('movie', 'person', 'name')


class VoteManager(models.Manager):
	def get_vote_or_unsaved_blank_vote(self, movie, user):
		try:
			return Vote.objects.get(movie=movie, user=user)

		except Vote.DoesNotExist:
			return Vote(movie=movie, user=user)

			
class Vote(models.Model):
	CHOICES = ((1,"like"),(-1,"dislike"))
	value = models.SmallIntegerField(choices = CHOICES)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='votes', on_delete = models.CASCADE )
	movie = models.ForeignKey(Movie, related_name='votes', on_delete = models.CASCADE)
	voted_on = models.DateField(auto_now = True)
	objects = VoteManager()
	#enforcing one person one vote for a particular movie
	class Meta:
		unique_together = ('user', 'movie')


class MovieImage(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True)
	image = models.ImageField(upload_to = 'images/%Y/%m/%d')
	uploaded = models.DateTimeField(auto_now_add = True)
	movie = models.ForeignKey(Movie, related_name="images",on_delete = models.CASCADE, blank=True)



# model to represent comment
class Comment(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="comments", on_delete=models.CASCADE)
	body = models.TextField()
	movie = models.ForeignKey(Movie, related_name="comments", on_delete=models.CASCADE)	
	created = models.DateField(auto_now_add=True)
	updated = models.DateField(auto_now=True)

	class Meta:
		ordering = ('created',)

	def __str__(self):
		return "comment by {} on {}".format(self.user.first_name, self.movie)

	#model ban gya hai
	# ab iske correspondin form
	#uske baad form ko detail view me add karna hai
	#uske baad createview se comment create karnabh

src/movies/forms.py
from django import forms
from django.db.models import Count
from .models import Vote, Movie, MovieImage, Comment
from django.contrib.auth import get_user_model 
#from django.core.validators import MaxValueValidator

class VoteForm(forms.ModelForm):
	user = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=get_user_model().objects.all())
	movie = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=Movie.objects.all())
	value = forms.ChoiceField(widget=forms.RadioSelect, choices=Vote.CHOICES, label='Vote')

	class Meta:
		model = Vote
		fields = ('value','user','movie')


class MovieImageForm(forms.ModelForm):
	user = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=get_user_model().objects.all())
	movie = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=Movie.objects.all())

	class Meta:
		model = MovieImage
		fields = ('user', 'movie','image')


class CommentForm(forms.ModelForm):
	user = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=get_user_model().objects.all())
	movie = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=Movie.objects.all())

	class Meta:
		model = Comment
		fields = ('user','movie', 'body')

src/movies/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.views.generic.edit import FormMixin
from .models import Movie,Person,Vote
from .forms import VoteForm,MovieImageForm, CommentForm
from django.core.exceptions import ValidationError
from taggit.models import Tag
#from .models import Vote
from django.db.models import F
from django.db.models import Count
from django.views.generic import TemplateView
from movies.service.elasticsearch import search_for_movies
# Create your views here.

#view displaying a list of movies
class MovieList(ListView):
	model = Movie
	paginate_by = 10
	sort_by = None
	tag = None

	def get_queryset(self):
		self.sort_by = self.request.GET.get('sort_by')
		self.tag = self.request.GET.get('tag')
		queryset = Movie.objects.all()
				

		print ("sort_by and tag are {} {}".format(self.sort_by, self.tag))
		if self.sort_by == 'Rating':
			queryset = queryset.order_by('-score')
		elif self.sort_by == 'Popularity':
			queryset = queryset.order_by('-visits')
		elif self.sort_by == 'Latest':
			queryset = queryset.order_by('-year')

		if self.tag is not None:
			tag = get_object_or_404(Tag, slug=self.tag)
			queryset = queryset.filter(tags__in=[tag])

		return queryset


	def get_context_data(self, **kwargs):
		ctx = super().get_context_data(**kwargs)
		ctx['tags'] = Movie.tags.all() 
		ctx['sort_by'] = self.sort_by
		ctx['tag'] = self.tag
		return ctx


class MovieDetail(DetailView):
	queryset = Movie.objects.all()

	#overriding the base class function
	def get_context_data(self, **kwargs):
		ctx = super().get_context_data(**kwargs)
		#updating the visits field of the movie object
		Movie.objects.filter(id=self.kwargs['pk']).update(visits=F('visits')+1)
		similar_tags = self.object.tags.values_list('id', flat=True)
		similar_movies = Movie.objects.filter(tags__in=similar_tags).exclude(id=self.object.id)
		similar_movies = similar_movies.annotate(same_tags=Count('tags')).order_by('-same_tags','-year')[:4]
		if self.request.user.is_authenticated:
			# to fetch object due to SingleObjectMixin of detailView
			imageform = MovieImageForm({'user': self.request.user.id, 'movie':self.kwargs['pk'] })
			commentform = CommentForm()
			vote = Vote.objects.get_vote_or_unsaved_blank_vote(movie=self.object, user=self.request.user)
			if vote.id:
				vote_form_url = reverse('UpdateVote', kwargs={'movie_id':vote.movie.id, 'pk':vote.id})
			else:
				vote_form_url = reverse('CreateVote', kwargs={'movie_id':self.object.id})

			#we could have done something like if form.isvalid in order to check the validity of the form
			vote_form = VoteForm(instance=vote)
			ctx['vote_form']=vote_form
			ctx['vote_form_url']=vote_form_url
			ctx['imageform']=imageform
			ctx['commentform']=commentform
		ctx['similar_movies'] = similar_movies
		return ctx
	

class CreateVote(LoginRequiredMixin, CreateView):
	form_class = VoteForm

	def get_initial(self):
		# url of the form : movie/<int:movie_id>/vote
		initial = super().get_initial()
		#for providing initial values to the form
		initial['user'] = self.request.user
		initial['movie'] = Movie.objects.get(id=self.kwargs['movie_id'])
		return initial

	#after success go to this url
	def get_success_url(self):
		movie_id = self.kwargs['movie_id']
		return reverse('detail', kwargs={'pk':movie_id})

	def form_valid(self, form):
		Movie.objects.filter(id=self.kwargs['movie_id']).update(score = F('score')+int(form.cleaned_data['value']))
		return super().form_valid(form)

	#if the form was invalid then go to this url
	def render_to_response(self, context=None, **response_kwargs):
		movie_id = self.kwargs['movie_id']
		return redirect(to = reverse('detail', kwargs={'pk':movie_id}))


class UpdateVote(LoginRequiredMixin, UpdateView):
	#url form - movie/<int:movie_id>/vote/<int:pk>
	form_class = VoteForm
	queryset = Vote.objects.all()

	def get_object(self, queryset=None):
		vote = super().get_object(queryset)
		user = self.request.user
		if vote.user != user:
			raise PermissionDenied('cannot change another person\'s vote')
		return vote	

	def form_valid(self, form):
		movie = Movie.objects.get(id=self.kwargs['movie_id'])
		if int(form.cleaned_data['value']) != Vote.objects.get(movie=movie,user=self.request.user).value:
			Movie.objects.filter(id=self.kwargs['movie_id']).update(score = F('score')+2*int(form.cleaned_data['value']))
		return super().form_valid(form)

	#after success go to this url
	def get_success_url(self):
		movie_id = self.kwargs['movie_id']
		return reverse('detail', kwargs={'pk':movie_id})

	#if the form was invalid then go to this url
	def render_to_response(self, context, **response_kwargs):
		return redirect(to = reverse('detail', kwargs={'pk':movie_id}))


class MovieImageUpload(LoginRequiredMixin, CreateView):
	form_class = MovieImageForm

	def render_to_rerrrrrrsponse(self, context, **response_kwargs):
		movie_id = self.kwargs['movie_id']
		return redirect(to=reverse('detail', kwargs={'pk':movie_id}))

	def get_success_url(self):
		movie_id = self.kwargs['movie_id']
		return reverse('detail', kwargs={'pk':movie_id})

class AddComment(LoginRequiredMixin, CreateView):
	form_class = CommentForm

	def get_initial(self):
		# url of the form : movie/<int:movie_id>/vote
		initial = super().get_initial()
		#for providing initial values to the form
		initial['user'] = self.request.user
		initial['movie'] = Movie.objects.get(id=self.kwargs['movie_id'])
		return initial.copy()

	#after success go to this url
	def get_success_url(self):
		movie_id = self.kwargs['movie_id']
		return reverse('detail', kwargs={'pk':movie_id})

	def get_form_kwargs(self):
		kwargs = {
			'initial': self.get_initial(),
			'prefix': self.get_prefix(),
		}

		if self.request.method in ('POST', 'PUT'):
			kwargs.update({
				'data': self.request.POST,
				'files': self.request.FILES,
			})
		print("kwargs are {}".format(kwargs))
		return super().get_form_kwargs()

	#if the form was invalid then go to this url
	def render_to_response(self, context=None, **response_kwargs):
		movie_id = self.kwargs['movie_id']
		return redirect(to = reverse('detail', kwargs={'pk':movie_id}))

class SearchView(TemplateView):
	template_name = 'movies/search.html'

	def get_context_data(self, **kwargs):
		query = self.request.GET.get('q',None)
		ctx = super().get_context_data(query=query, **kwargs)
		if query:
			results = search_for_movies(query)
			ctx['hits'] = results
		return ctx

src/templates/movies/detail.html
{% extends "base.html" %}
{% block title %}{{object.title}}- {{block.super}} {% endblock %}

{% block content %}
	<div class="col">
		<h1>{{object}}</h1>
		<p class="lead">{{object.plot}}</p>
	</div>
	<p>Tags= {{object.tags.all|join:", "}}</p>
	<ul class="movie-image list-inline">
		{% for image in object.images.all %}
			<li class="list-inline-item">
				<p>{{image.image.url}}</p>
				<img src="{{image.image.url}}">
			</li>
		{% endfor %}
	</ul>
	<p>Similar Movies - </p>
	<ul>
		{% for movie in similar_movies%}
			<li>
				<a href="{% url "detail" movie.id%}">{{movie}}</a>
			</li>
		{% endfor %}
	</ul>
	<div>
		{% if commentform %}
			<form method="post" action="{% url "AddComment" movie_id=object.id %}">
				{% csrf_token %}
				{{commentform.as_p}}
				<button class="btn btn-primary" >Comment</button>
			</form>
		{% else %}
			<p>Log-in to make a comment </p>	
		{% endif %}
	</div>
{% endblock %}
{% block sidebar %}
	<div>
		<p>This movie is rated : </p>
		<span class="badge badge-primary">{{object.get_rating_display}} </span>
	</div>
	<div>
		<h2>Score : {{object.score}} </h2>
	</div>
	<div>
		{% if imageform %}
			<h2>Upload New Image</h2>
			<form method="post" enctype="multipart/form-data" action="{% url "MovieImageUpload" movie_id=object.id %}">
				{% csrf_token %}
				{{imageform.as_p}}
				<p><button class="btn btn-primary">Upload</button></p>	
			</form>
		{% endif %}
	</div>
	<div>
		{% if vote_form %}
			<form method="post" action="{{ vote_form_url }}">
				{% csrf_token %}
				{{vote_form.as_p}}
				<button class="btn btn-primary" >Vote</button>
			</form>
		{% else %}
			<p>Log-in to vote for this movie </p>	
		{% endif %}
	</div>	
{% endblock %}

src/templates/movies/list.html
{% extends "base.html" %}
{% block title %}All the movies{% endblock %}

{% block content %}

	<nav>
		<ul>
			<p>tag value is {{tag}}</p>
			<li><a href="{% url 'list' %}?sort_by=Rating&tag={{tag}}">Rating</a></li>
			<li><a href="{% url 'list' %}?sort_by=Popularity&tag={{tag}}">Popularity</a></li>
			<li><a href="{% url 'list' %}?sort_by=Latest&tag={{tag}}">Latest</a></li>
		</ul>
	</nav>
	<nav>
		<ul>
			{% for tag in tags%}
				<li><a href="{% url 'list'%}?tag={{tag.slug}}&sort_by={{sort_by}}">{{tag.name}}</a></li>
			{% endfor %}
		</ul>
	</nav>
	<ul>
		{% for movie in object_list %}
			<li>

				<a href="{% url "detail" movie.id%}">{{movie}}</a>
			</li>
		{% empty %}
			<p>No movies to show currently</p>	
		{% endfor %}

	</ul>
	<!--adding pagination -->
	{% if is_paginated %}
		<nav>
			<ul class="pagination">
				<li class="page-item"><a href="{% url 'list' %}?page=1" class="page-link">First</a></li>
				{% if page_obj.has_previous %}
					<li class="page-item"><a href="{% url 'list' %}?page={{page_obj.previous_page_number}}" class="page-link">{{page_obj.previous_page_number}}</a></li>
				{% endif %}
				<li class="page-item active"><a href="{% url 'list' %}?page={{page_obj.number}}" class="page-link">{{page_obj.number}}</a></li>
				{% if page_obj.has_next %}
					<li class="page-item"><a href="{% url 'list' %}?page={{page_obj.next_page_number}}" class="page-link">{{page_obj.next_page_number}}</a></li>
				{% endif %}
				<li class="page-item"><a href="{% url 'list' %}?page=last" class="page-link">Last</a></li>
			</ul>	
		</nav>
	{% endif %}

{% endblock %}

src/templates/movies/search.html
{% extends "base.html" %}

{% block content %}
	<h2>Search</h2>
	<form method="get" class="form-inline">
		<input placeholder="Search" type="search" name="q" value="{{query}}">
		<button type="submit" class="btn btn-primary">Search</button>
	</form>
	{% if query %}
		<h3>Results from search query '{{query}}'</h3>
		<ul>
			{% for hit in hits %}
			<li><a href="{% url 'detail' pk=hit.id%} ">{{hit.title}}</a></li>
			{% empty %}
				<p>No results found</p>
			{% endfor %}
		</ul>
	{% endif %}
{% endblock %}